services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8010:8000"
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres_db:5432/lab_db
      - HF_SPACE_ID=Oleg0509/pets
      - HF_TOKEN=hf_... # Uzupełnij swój token
    depends_on:
      - postgres_db
      - otel-collector
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - monitoring-net
    restart: unless-stopped

  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=lab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - monitoring-net
    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.103.1
    container_name: otel-collector
    command: [ "--config=/etc/otel-config.yaml" ]
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4316:4316"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - tempo
      - loki
    networks:
      - monitoring-net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-net
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4319:4319"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    networks:
      - monitoring-net
    restart: unless-stopped

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - monitoring-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - monitoring-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9080/ready"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
      - tempo
      - loki
      - promtail
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - monitoring-net
    restart: unless-stopped

volumes:
  postgres_data:
  grafana-storage:

networks:
  monitoring-net:
    driver: bridge
